/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Agoric: typeof import('./src/components/Event/Task/CollectWallet/Cosmos/Agoric.vue')['default']
    Archway: typeof import('./src/components/Event/Task/CollectWallet/Cosmos/Archway.vue')['default']
    Banner: typeof import('./src/components/Banner/index.vue')['default']
    Binance: typeof import('./src/components/Event/Task/Wallet/Evm/Binance.vue')['default']
    Card: typeof import('./src/components/Event/Card/index.vue')['default']
    Cosmos: typeof import('./src/components/Event/Task/CollectWallet/Cosmos/Cosmos.vue')['default']
    DexLpProvision: typeof import('./src/components/Event/Task/Osmosis/DexLpProvision.vue')['default']
    DexTradingVolume: typeof import('./src/components/Event/Task/Osmosis/DexTradingVolume.vue')['default']
    DexTxnCount: typeof import('./src/components/Event/Task/Osmosis/DexTxnCount.vue')['default']
    Duration: typeof import('./src/components/Event/Duration/index.vue')['default']
    Ethereum: typeof import('./src/components/Event/Task/CollectWallet/Evm/Ethereum.vue')['default']
    EventDescription: typeof import('./src/components/Event/EventDescription/index.vue')['default']
    EventParticipant: typeof import('./src/components/Event/EventParticipant/index.vue')['default']
    EventRefer: typeof import('./src/components/Event/EventRefer/index.vue')['default']
    EventRewards: typeof import('./src/components/Event/EventRewards/index.vue')['default']
    Faq: typeof import('./src/components/Faq/index.vue')['default']
    Follow: typeof import('./src/components/Event/Task/Social/Twitter/Follow.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    FyreXp: typeof import('./src/components/Event/Task/CollectInput/FyreXp.vue')['default']
    Hyperersign: typeof import('./src/components/Event/Task/TokenHolding/Cosmos/Hyperersign.vue')['default']
    Hypersign: typeof import('./src/components/Event/Task/Stacking/Cosmos/Hypersign.vue')['default']
    Join: typeof import('./src/components/Event/Task/Social/Discord/Join.vue')['default']
    Like: typeof import('./src/components/Event/Task/Social/Twitter/Like.vue')['default']
    Loader: typeof import('./src/components/Loader/index.vue')['default']
    LpProvision: typeof import('./src/components/Event/Task/Osmosis/LpProvision.vue')['default']
    ModelPopup: typeof import('./src/components/ModelPopup/index.vue')['default']
    Nibiru: typeof import('./src/components/Event/Task/CollectWallet/Cosmos/Nibiru.vue')['default']
    Omniflex: typeof import('./src/components/Event/Task/CollectWallet/Cosmos/Omniflex.vue')['default']
    Osmosis: typeof import('./src/components/Event/Task/CollectWallet/Cosmos/Osmosis.vue')['default']
    Polygon: typeof import('./src/components/Event/Task/CollectWallet/Evm/Polygon.vue')['default']
    PullRequest: typeof import('./src/components/Event/Task/Social/Github/PullRequest.vue')['default']
    Quiz: typeof import('./src/components/Event/Task/CollectInput/Quiz.vue')['default']
    Retweet: typeof import('./src/components/Event/Task/Social/Twitter/Retweet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Secret: typeof import('./src/components/Event/Task/CollectWallet/Cosmos/Secret.vue')['default']
    SlickSlider: typeof import('./src/components/Banner/slick-slider.vue')['default']
    Slider: typeof import('./src/components/Banner/slider.vue')['default']
    Stargraze: typeof import('./src/components/Event/Task/CollectWallet/Cosmos/Stargraze.vue')['default']
    SupportedChain: typeof import('./src/components/SupportedChain/index.vue')['default']
    Tabs: typeof import('./src/components/Navigation/Tabs.vue')['default']
    Task: typeof import('./src/components/Event/Task/index.vue')['default']
    Text: typeof import('./src/components/Event/Task/CollectInput/Text.vue')['default']
    TxnCount: typeof import('./src/components/Event/Task/Osmosis/TxnCount.vue')['default']
    Url: typeof import('./src/components/Event/Task/CollectInput/Url.vue')['default']
    VisitUrl: typeof import('./src/components/Event/Task/CollectInput/VisitUrl.vue')['default']
  }
}
