/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner/index.vue')['default']
    Binance: typeof import('./src/components/Event/Task/Wallet/Evm/Binance.vue')['default']
    Duration: typeof import('./src/components/Event/Duration/index.vue')['default']
    EventDescription: typeof import('./src/components/Event/EventDescription/index.vue')['default']
    EventParticipant: typeof import('./src/components/Event/EventParticipant/index.vue')['default']
    EventRefer: typeof import('./src/components/Event/EventRefer/index.vue')['default']
    EventRewards: typeof import('./src/components/Event/EventRewards/index.vue')['default']
    Faq: typeof import('./src/components/Faq/index.vue')['default']
    Follow: typeof import('./src/components/Event/Task/Social/Twitter/Follow.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Join: typeof import('./src/components/Event/Task/Social/Discord/Join.vue')['default']
    Like: typeof import('./src/components/Event/Task/Social/Twitter/Like.vue')['default']
    Loader: typeof import('./src/components/Loader/index.vue')['default']
    ModelPopup: typeof import('./src/components/ModelPopup/index.vue')['default']
    Retweet: typeof import('./src/components/Event/Task/Social/Twitter/Retweet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlickSlider: typeof import('./src/components/Banner/slick-slider.vue')['default']
    Slider: typeof import('./src/components/Banner/slider.vue')['default']
    SupportedChain: typeof import('./src/components/SupportedChain/index.vue')['default']
    Tabs: typeof import('./src/components/Navigation/Tabs.vue')['default']
    Task: typeof import('./src/components/Event/Task/index.vue')['default']
    Text: typeof import('./src/components/Event/Task/Collect/Input/Text.vue')['default']
    Url: typeof import('./src/components/Event/Task/Collect/Input/Url.vue')['default']
    VisitUrl: typeof import('./src/components/Event/Task/Collect/Input/VisitUrl.vue')['default']
  }
}
