apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyre-ui
  namespace: hypermine-development
spec:
  selector:
    matchLabels:
      app: fyre-ui
  template:
    metadata:
      labels:
        app: fyre-ui
    spec:
      containers:
        - name: fyre-ui
          image: __GOOGLE_ARTIFACT_URL__/__GOOGLE_PROJECT_ID__/__GOOGLE_ARTIFACT_REPO__/fyre-frontend:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9002
          env:
            - name: VITE_API_ENDPOINT
              value: __VITE_API_ENDPOINT__
            - name: VITE_API_TOKEN
              value: __VITE_API_TOKEN__
            - name: VITE_APP_AUTH0_DOMAIN
              value: __VITE_APP_AUTH0_DOMAIN__
            - name: VITE_APP_AUTH0_CLIENT_ID
              value: __VITE_APP_AUTH0_CLIENT_ID__
            - name: VITE_APP_TELEGRAM_BOT_ID
              value: __VITE_APP_TELEGRAM_BOT_ID__
---
apiVersion: v1
kind: Service
metadata:
  name: fyre-ui-svc
  namespace: hypermine-development

spec:
  type: NodePort
  selector:
    app: fyre-ui
  ports:
    - port: 9002
      targetPort: 80