apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyre-new-ui
  namespace: hypermine-development
spec:
  selector:
    matchLabels:
      app: fyre-new-ui
  template:
    metadata:
      labels:
        app: fyre-new-ui
    spec:
      containers:
        - name: fyre-new-ui
          image: __GOOGLE_ARTIFACT_URL__/__GOOGLE_PROJECT_ID__/__GOOGLE_ARTIFACT_REPO__/fyre-new-ui:__LATEST_RELEASE_TAG__
          imagePullPolicy: Always
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: fyre-new-ui-svc
  namespace: hypermine-development

spec:
  type: NodePort
  selector:
    app: fyre-new-ui
  ports:
    - port: 9002
      targetPort: 80
