apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyre-new-ui
  namespace: hypermine-development
spec:
  selector:
    matchLabels:
      app: fyre-new-ui
  template:
    metadata:
      labels:
        app: fyre-new-ui
    spec:
      containers:
        - name: fyre-new-ui
          image: __GOOGLE_ARTIFACT_URL__/__GOOGLE_PROJECT_ID__/__GOOGLE_ARTIFACT_REPO__/fyre-new-ui:__LATEST_RELEASE_TAG__
          imagePullPolicy: Always
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 9002
          env:
            - name: NODE_ENV
              value: __NODE_ENV__
            - name: VUE_APP_DESC
              value: __VUE_APP_DESC__
            - name: VUE_APP_EXPLORER_BASE_URL
              value: __VUE_APP_EXPLORER_BASE_URL__
            - name: VUE_APP_NODE_SERVER_BASE_URL_REST
              value: __VUE_APP_NODE_SERVER_BASE_URL_REST__
            - name: VUE_APP_STUDIO_SERVER_BASE_URL
              value: __VUE_APP_STUDIO_SERVER_BASE_URL__
            - name: VUE_APP_STUDIO_SERVER_BASE_WS
              value: __VUE_APP_STUDIO_SERVER_BASE_WS__
            - name: VUE_APP_TITLE
              value: __VUE_APP_TITLE__
            - name: VUE_APP_VERSION
              value: __VUE_APP_VERSION__
            - name: VUE_APP_WEB_WALLET_ADDRESS
              value: __VUE_APP_WEB_WALLET_ADDRESS__
---
apiVersion: v1
kind: Service
metadata:
  name: fyre-new-ui-svc
  namespace: hypermine-development

spec:
  type: NodePort
  selector:
    app: fyre-new-ui
  ports:
    - port: 9002
      targetPort: 80
