name: Fyre UI Build and Deploy Pipeline

on:
  push:
    branches:
      - "devops"

jobs:
  Build-Pipeline:
    runs-on: ubuntu-22.04
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: install gcloud cli tools
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GOOGLE_PROJECT_ID}}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true
      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker Auth"
        env:
          GOOGLE_ARTIFACT_URL: ${{secrets.GOOGLE_ARTIFACT_URL}}
        run: gcloud auth configure-docker $GOOGLE_ARTIFACT_URL
      - name: "Docker Build and Push"
        env:
          GOOGLE_PROJECT_ID: ${{secrets.GOOGLE_PROJECT_ID}}
          GOOGLE_ARTIFACT_URL: ${{secrets.GOOGLE_ARTIFACT_URL}}
          GOOGLE_ARTIFACT_REPO: ${{secrets.GOOGLE_ARTIFACT_REPO}}
          VITE_API_ENDPOINT: ${{ vars.VITE_API_ENDPOINT }}
          VITE_API_TOKEN: ${{ vars.VITE_API_TOKEN }}
          VITE_APP_AUTH0_DOMAIN: ${{ vars.VITE_APP_AUTH0_DOMAIN }}
          VITE_APP_AUTH0_CLIENT_ID: ${{ vars.VITE_APP_AUTH0_CLIENT_ID }}
          VITE_APP_TELEGRAM_BOT_ID: ${{ vars.VITE_APP_TELEGRAM_BOT_ID }}
        run:

          find Dockerfile -type f -exec sed  -i -e "s#__VITE_API_ENDPOINT__#${{ vars.VITE_API_ENDPOINT }}#" {} \;

          find Dockerfile -type f -exec sed  -i -e "s#__VITE_API_TOKEN__#${{ vars.VITE_API_TOKEN }}#" {} \;

          find Dockerfile -type f -exec sed  -i -e "s#__VITE_APP_AUTH0_DOMAIN__#${{ vars.VITE_APP_AUTH0_DOMAIN }}#" {} \;

          find Dockerfile -type f -exec sed  -i -e "s#__VITE_APP_AUTH0_CLIENT_ID__#${{ vars.VITE_APP_AUTH0_CLIENT_ID }}#" {} \;

          find Dockerfile -type f -exec sed  -i -e "s#__VITE_APP_TELEGRAM_BOT_ID__#${{ vars.VITE_APP_TELEGRAM_BOT_ID }}#" {} \;

          docker build -t $GOOGLE_ARTIFACT_URL/$GOOGLE_PROJECT_ID/$GOOGLE_ARTIFACT_REPO/fyre-ui:latest  .

          docker push $GOOGLE_ARTIFACT_URL/$GOOGLE_PROJECT_ID/$GOOGLE_ARTIFACT_REPO/fyre-ui:latest

  Deploy-Pipeline:
    needs: [Build-Pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: install gcloud cli tools
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GOOGLE_PROJECT_ID}}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true
      - name: "Configure kubectl"
        run: gcloud container clusters get-credentials hypermine-gke --region=asia-south1
      - name: "Prune Deployment"
        run: kubectl delete deployment fyre-ui -n hypermine-development
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__GOOGLE_ARTIFACT_URL__/${{ secrets.GOOGLE_ARTIFACT_URL }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__GOOGLE_ARTIFACT_REPO__/${{ secrets.GOOGLE_ARTIFACT_REPO }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__GOOGLE_PROJECT_ID__/${{ secrets.GOOGLE_PROJECT_ID }}/g'' {} \;

      - name: "Deploy to GKE"
        run: kubectl apply -f .deploy/deployment.yaml



